service: pocnodeserveless
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-typescript-express
  
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  express:
    handler: app/server.handler
    name: api
    events:
      - http: ANY /{proxy+}  
  lambda:
    handler: app/lambda.handler
    events:
      - http: GET /lambda
        
      